// <auto-generated />
using System;
using HRMBackend.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRMBackend.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240104063839_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRMBackend.DTO.Applicant.ApplicantDTO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("hasSubmittedApplication")
                        .HasColumnType("bit");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Applicant");
                });

            modelBuilder.Entity("HRMBackend.DTO.Applicant.ApplicantHasToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("applicantID")
                        .HasColumnType("int");

                    b.Property<string>("urlToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("applicantID")
                        .IsUnique();

                    b.ToTable("ApplicantHasToken");
                });

            modelBuilder.Entity("HRMBackend.DTO.Applicant.ApplicantHasToken", b =>
                {
                    b.HasOne("HRMBackend.DTO.Applicant.ApplicantDTO", "applicant")
                        .WithOne("applicantHasToken")
                        .HasForeignKey("HRMBackend.DTO.Applicant.ApplicantHasToken", "applicantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("applicant");
                });

            modelBuilder.Entity("HRMBackend.DTO.Applicant.ApplicantDTO", b =>
                {
                    b.Navigation("applicantHasToken")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
