// <auto-generated />
using System;
using HRMBackend.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRMBackend.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240109182627_create_sms_campaign_receipients_migration")]
    partial class create_sms_campaign_receipients_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRMBackend.Model.Applicant.Applicant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("hasSubmittedApplication")
                        .HasColumnType("bit");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Applicant");
                });

            modelBuilder.Entity("HRMBackend.Model.Applicant.ApplicantHasOTP", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("applicantID")
                        .HasColumnType("int");

                    b.Property<string>("contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("otp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("applicantID")
                        .IsUnique();

                    b.ToTable("ApplicantHasOTP");
                });

            modelBuilder.Entity("HRMBackend.Model.SMS.SMSCampaignHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("campaignName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("receipients")
                        .HasColumnType("int");

                    b.Property<int>("smsTemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("smsTemplateId");

                    b.ToTable("SMSCampaignHistory");
                });

            modelBuilder.Entity("HRMBackend.Model.SMS.SMSCampaignReceipient", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("campaignHistoryId")
                        .HasColumnType("int");

                    b.Property<string>("contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Status => Pending or Successful or Failed");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("campaignHistoryId");

                    b.ToTable("SMSCampaignReceipient");
                });

            modelBuilder.Entity("HRMBackend.Model.SMS.SMSTemplate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("readOnly")
                        .HasColumnType("bit");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("SMSTemplate");
                });

            modelBuilder.Entity("HRMBackend.Model.Applicant.ApplicantHasOTP", b =>
                {
                    b.HasOne("HRMBackend.Model.Applicant.Applicant", "applicant")
                        .WithOne("otp")
                        .HasForeignKey("HRMBackend.Model.Applicant.ApplicantHasOTP", "applicantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("applicant");
                });

            modelBuilder.Entity("HRMBackend.Model.SMS.SMSCampaignHistory", b =>
                {
                    b.HasOne("HRMBackend.Model.SMS.SMSTemplate", "smsTemplate")
                        .WithMany("smsHistory")
                        .HasForeignKey("smsTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("smsTemplate");
                });

            modelBuilder.Entity("HRMBackend.Model.SMS.SMSCampaignReceipient", b =>
                {
                    b.HasOne("HRMBackend.Model.SMS.SMSCampaignHistory", "campaignHistory")
                        .WithMany("smsReceipients")
                        .HasForeignKey("campaignHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("campaignHistory");
                });

            modelBuilder.Entity("HRMBackend.Model.Applicant.Applicant", b =>
                {
                    b.Navigation("otp")
                        .IsRequired();
                });

            modelBuilder.Entity("HRMBackend.Model.SMS.SMSCampaignHistory", b =>
                {
                    b.Navigation("smsReceipients");
                });

            modelBuilder.Entity("HRMBackend.Model.SMS.SMSTemplate", b =>
                {
                    b.Navigation("smsHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
